services:
    app:
        build:
            context: .
            dockerfile: .docker/frankenphp/Dockerfile
            target: prod
        ports:
            - ${HTTP_PORT:-88}:80
            - ${HTTPS_PORT:-448}:443
        environment:
            APP_RUNNER: "frankenphp"
            FRANKENPHP_CONFIG: |
                {
                    worker /srv/www/index.php
                }
            SERVER_NAME: localhost
            XDEBUG_MODE: "off"
        volumes:
            - ./:/srv
            - .docker/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile
