services:
    app:
        build:
            target: dev
        environment:
            CADDY_DEBUG: "debug"
            # Xdebug
            XDEBUG_SESSION: 1
            XDEBUG_CONFIG: "idekey=docker"
            XDEBUG_MODE: "debug"
            PHP_IDE_CONFIG: "serverName=docker"
            # Nette
            NETTE_DEBUG: "true"
        volumes:
            - ./:/srv
            - .docker/Caddyfile:/etc/frankenphp/Caddyfile
