services:
    app:
        build:
            target: dev
        ports:
            - ${XDEBUG_PORT:-9003}:9003
        environment:
            CADDY_DEBUG: "debug"
            # Xdebug
            XDEBUG_SESSION: 1
            XDEBUG_CONFIG: "idekey=docker"
            XDEBUG_MODE: "debug"
            PHP_IDE_CONFIG: "serverName=docker"
            # Server config with hot reloading
            FRANKENPHP_CONFIG: |
                {
                    hot_reload app/** assets/** www/** config/** libs/**
                    worker {
                        file /srv/www/index.php
                        watch
                    }
                }
            MERCURE_EXTRA_DIRECTIVES: |
                debug
                ui
            MERCURE_JWT_SECRET: ${MERCURE_JWT_SECRET}
            # Nette
            NETTE_DEBUG: "true"
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway
